export default () => {
  return [{
    property: 'og:title',
    keyName: 'title'
  }, {
    property: 'og:type',
    keyName: 'type'
  }, {
    property: 'og:logo',
    keyName: 'logo'
  }, {
    property: 'og:image',
    keyName: 'image'
  }, {
    property: 'og:image:url',
    keyName: 'imageURL'
  }, {
    property: 'og:image:secure_url',
    keyName: 'imageSecureURL'
  }, {
    property: 'og:image:width',
    keyName: 'imageWidth'
  }, {
    property: 'og:image:height',
    keyName: 'imageHeight'
  }, {
    property: 'og:image:type',
    keyName: 'imageType'
  }, {
    property: 'og:url',
    keyName: 'url'
  }, {
    property: 'og:audio',
    keyName: 'audio'
  }, {
    property: 'og:audio:url',
    keyName: 'audioURL'
  }, {
    property: 'og:audio:secure_url',
    keyName: 'audioSecureURL'
  }, {
    property: 'og:audio:type',
    keyName: 'audioType'
  }, {
    property: 'og:description',
    keyName: 'description'
  }, {
    property: 'og:determiner',
    keyName: 'determiner'
  }, {
    property: 'og:locale',
    keyName: 'locale'
  }, {
    property: 'og:locale:alternate',
    keyName: 'localeAlternate'
  }, {
    property: 'og:site_name',
    keyName: 'siteName'
  }, {
    property: 'og:product:retailer_item_id',
    keyName: 'productRetailerItemId'
  }, {
    property: 'og:product:price:amount',
    keyName: 'productPriceAmount'
  }, {
    property: 'og:product:price:currency',
    keyName: 'productPriceCurrency'
  }, {
    property: 'og:product:availability',
    keyName: 'productAvailability'
  }, {
    property: 'og:product:condition',
    keyName: 'productCondition'
  }, {
    property: 'og:price:amount',
    keyName: 'priceAmount'
  }, {
    property: 'og:price:currency',
    keyName: 'priceCurrency'
  }, {
    property: 'og:availability',
    keyName: 'availability'
  }, {
    property: 'og:video',
    keyName: 'video'
  }, {
    property: 'og:video:url', // An alternative to 'og:video'
    keyName: 'video'
  }, {
    property: 'og:video:secure_url',
    keyName: 'videoSecureURL'
  }, {
    property: 'og:video:actor:id',
    keyName: 'videoActorId'
  }, {
    property: 'og:video:width',
    keyName: 'videoWidth'
  }, {
    property: 'og:video:height',
    keyName: 'videoHeight'
  }, {
    property: 'og:video:type',
    keyName: 'videoType'
  }]
}
